AppCat/urls.py
from django.urls import path
from AppCat.views import *

urlpatterns = [
    path("",inicio, name="Home"),

    path("login/", iniciar_sesion, name="Iniciar Sesion"),
    path("signup/", registro, name="Registrarse"),
    path("logout/", cerrar_sesion, name="Cerrar Sesion"),
    path("edit/", editarPerfil, name="Editar Usuario"),
    path("contra/", CambiarContra.as_view(), name="Cambiar Contraseña"),
    path("avatar/", agregar_avatar, name="Agregar Avatar")

    path("nuevo_cliente", agregar_Cliente),
    path("nueva_compra",agregar_compra),
    path("crear_presupuesto",agregar_presupuesto),
    path("buscar_cliente", buscar_cliente),
    path("resultadoCli",resultado_busqueda),

    path("ver_compra",ver_compra),
    path("ver_cliente",ver_cliente),
    path("ver_presupuesto",ver_presupuesto),
    
    path("lista_compras/", CompraLista.as_view()),
    path("nuevo_presupuesto/", presupuesto.as_view()),
    path("editar_presupuesto/<int:pk>", PresupuestoEditar.as_view()),
    path("borrar_presupuesto/<int:pk>", presupuestoBorrarBorrar.as_view())
    

]

ProyectoCat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("AppCat", include("AppCat.urls"))
]
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCat/models.py
from django.db import models
from django.contrib.auth.models import User


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    edad = models.IntegerField()
    direccion = models.CharField (max_length=100)

    def __str__(self):
        return self.nombre

class Compra(models.Model):
    fecha = models.DateField()
    productos =models.CharField(max_length=500)
    direccion = models.CharField (max_length=100)
    nombreFiesta = models.CharField(max_length=50)
    cliente = models.ForeignKey("Cliente", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.nombreFiesta
    
class presupuesto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    productos = models.CharField(max_length=500)
    direccion = models.CharField(max_length=100)
    cliente = models.ForeignKey("Cliente", on_delete=models.CASCADE)


    def __str__(self) :
        return self.nombre
    
class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

AppCat/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
class ClienteForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    edad = forms.IntegerField()
    direccion = forms.CharField (max_length=100)
    
class CompraForm(forms.Form):
    fecha = forms.DateField()
    productos =forms.CharField()
    direccion = forms.CharField (max_length=100)
    nombreFiesta = forms.CharField(max_length=50)
    cliente = forms.CharField(max_length=50)

class presupuestoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    precio = forms.IntegerField()
    productos = forms.CharField(max_length=500)
    direccion = forms.CharField(max_length=100)
    cliente = forms.CharField(max_length=50)

class EditarClienteForm(UserChangeForm):

    password = None

    class Meta:
        model = User
        fields = ["first_name", "last_name",  "email"]

class AvatarFormulario(forms.Form):
    imagen = forms.ImageField()
class RegistroUsuario(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name",  "email", "password1", "password2"]


class EditarUsuario(UserChangeForm):

    password = None

    class Meta:
        model = User
        fields = ["first_name", "last_name",  "email"]

AppCat/views.py
from django.shortcuts import render
from AppCat.forms import *
from AppCat.models import *
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def inicio(request):
    return render(request,"AppCat/inicio.html")

@login_required
def agregar_Cliente(request):
    if request.method =="POST":
        formulario = ClienteForm(request.POST)
        if formulario.is_valid():
            info_dict =  formulario.cleaned_data
            nuevo_clienete = Cliente(nombre = info_dict["nombre"],edad = info_dict["edad"], direccion=info_dict["direccion"])
            nuevo_clienete.save()
            return render(request,"inicio.html")
    else:
        formulario = ClienteForm()
    
    return render(request, "AppCat/nuevo_cliente.html",{"form":formulario})

@login_required
def agregar_presupuesto(request):
    if request.method =="POST":
        formulario = presupuestoForm(request.POST)
        if formulario.is_valid():
            info_dict =  formulario.cleaned_data
            nuevo_presupuesto = presupuestoForm(nombre = info_dict["nombre"],precio = info_dict["precio"], direccion=info_dict["direccion"], producto = info_dict["producto"],cliente=info_dict["cliente"])
            nuevo_presupuesto.save()
            return render(request,"inicio.html")
    else:
        formulario = presupuestoForm()
    
    return render(request, "AppCat/crear_presupuesto.html",{"form":formulario})

@login_required
def agregar_compra(request):
    if request.method =="POST":
        formulario = CompraForm(request.POST)
        if formulario.is_valid():
            info_dict =  formulario.cleaned_data
            nuevo_presupuesto = CompraForm(nombreFiesta = info_dict["nombreFiesta"],fecha = info_dict["fecha"], direccion=info_dict["direccion"], producto = info_dict["producto"],cliente=info_dict["cliente"])
            nuevo_presupuesto.save()
            return render(request,"inicio.html")
    else:
        formulario = CompraForm()
    
    return render(request, "AppCat/nueva_compra.html",{"form":formulario})

def buscar_cliente(request):

    return render(request,"AppCat/buscar_cliente.html")

def resultado_busqueda(request):
    cliente = request.GET.get("Nombre Cliente")

    nombre = Cliente.object.filter(nombre_icontains=cliente)

    return render(request, "AppCat/resultadoBusqueda.html", {"nombre":nombre})

def iniciar_sesion(request):

    if request.method == "POST":

        formulario = AuthenticationForm(request, data = request.POST) #almacena la informacion que se ha puesto en el form

        if formulario.is_valid():

            info_dic = formulario.cleaned_data #convierte la info del form a un diccionario de python

            usuario = authenticate(username=info_dic["username"], password=info_dic["password"])

            if usuario is not None: #que el usuario existe!!!

                login(request, usuario)

                return render(request, "inicio.html", {"mensaje":f"Bienvenido {usuario}"})
        
            
        else:

            return render(request, "inicio.html", {"mensaje":"Credenciales Incorrectas"})
        
    else:

        formulario = AuthenticationForm()

    return render(request, "registro/inicio_sesion.html", {"formu":formulario})

# Agregar Avatar
@login_required
def agregar_avatar(request):

    if request.method == "POST":

        formulario = AvatarFormulario(request.POST, request.FILES)

        if formulario.is_valid():

            info = formulario.cleaned_data

            usuario_actual = User.objects.get(username=request.user)
            nuevo_avatar = Avatar(usuario=usuario_actual, imagen=info["imagen"])

            nuevo_avatar.save()
            return render(request, "inicio.html", {"mensaje":"Has creado tu avatar"})
    
    else:

        formulario = AvatarFormulario()


    return render(request, "registro/nuevo_avatar.html", {"formu":formulario})

# Vista de editar el perfil
@login_required
def editarPerfil(request):

    usuario = request.user #cual es el usuario que tiene la sesion activa

    if request.method == 'POST':

        miFormulario = EditarUsuario(request.POST)

        if miFormulario.is_valid():

            informacion = miFormulario.cleaned_data

            usuario.email = informacion['email']
            usuario.last_name = informacion['last_name']
            usuario.first_name = informacion['first_name']

            usuario.save()

            return render(request, "inicio.html")

    else:

        miFormulario = EditarUsuario(initial={'username':usuario.username, 'first_name':usuario.first_name,
                                                'last_name':usuario.last_name, 'email': usuario.email})


    return render(request, "registro/editar_usuario.html", {"formu":miFormulario})


def cerrar_sesion(request):

    logout(request)

    return render(request, "inicio.html", {"mensaje":"Has cerrado sesión con éxito."})


def ver_presupuesto(request):

    todos_presupuesto = presupuesto.objects.all() #obtener todos los estudiantes que existen

    return render(request, "ver_presupuesto.html", {"total":todos_presupuesto})

@login_required
def actualizar_presupuesto(request, presupuesto):

    presupuesto_elegido = presupuesto.objects.get(id=presupuesto)

    if request.method == "POST":

        formulario = presupuestoForm(request.POST) #almacena la informacion que se ha puesto en el form

        if formulario.is_valid():

            info_dic = formulario.cleaned_data #convierte la info del form a un diccionario de python

            #Cambiado los datos de un objeto que ya se habia creado!!
            presupuesto_elegido.nombre = info_dic["nombre"]
            presupuesto_elegido.precio = info_dic["precio"]
            presupuesto_elegido.direccion = info_dic["direccion"]
            presupuesto_elegido.producto = info_dic["producto"]
            presupuesto_elegido.cliente = info_dic["cliente"]


            presupuesto_elegido.save()

            return render(request, "inicio.html")
        
    else:

        formulario = presupuestoForm(initial={"nombre":presupuesto_elegido.nombre, "precio":presupuesto_elegido.precio,"direccion":presupuesto_elegido.direccion, "producto":presupuesto_elegido.producto,"cliente":presupuesto_elegido.cliente })

    return render(request, "estudiantes/actualizar_presupuesto.html", {"formu":formulario})

@login_required
def borrar_presupuesto(request, presupuesto_info):

    presupuesto_elegido = presupuesto.objects.get(id=presupuesto_info)

    presupuesto.delete()

    return render(request, "inicio.html")

@login_required
def ver_compra(request):

    todos_compra = Compra.objects.all()

    return render(request, "cursos/ver_compra.html", {"total":todos_compra})

def borrar_presupuesto(request, presupuesto_info):

    presupuesto_elegido = Compra.objects.get(id=presupuesto_info)

    presupuesto_elegido.delete()

    return render(request, "inicio.html")

def ver_cliente(request):

    return render(request, "ver_client.html")

class CompraLista(ListView):
    model = Compra
    template_name = "lista_de_compras.html"

class CompraCrear(LoginRequiredMixin, CreateView):
    model = Compra
    template_name = "nueva_compra.html"
    fields = ["nombre_fiesta", "cliente"]
    success_url = "/AppCat/ver_compra/"

class PresupuestoEditar(UpdateView):
    model = presupuesto
    template_name = "crear_presupuesto.html"
    fields = ["nombre", "cliente"]
    success_url = "/AppCoder/"

class presupuestoBorrar(DeleteView):
    model = presupuesto
    template_name = "borrar_presupuesto.html"
    success_url = "/AppCat/"

class CambiarContra(LoginRequiredMixin, PasswordChangeView):
    template_name = "registro/cambiar_contra.html"
    success_url = "/AppCat/"

AppCat/templates/actualizar_presupuesto.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="post">{%csrf_token%}
    
    {{form}}

    <input type="submit" value="Guardar">

</form>
{% endblock %}

AppCat/templates/borrar_presupuesto.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="post"> {% csrf_token %}

<p>¿Quiere eliminar el presupuesto: {{object}}? </p>

<input type="submit" value="Eliminar">

</form>

{% endblock %}

AppCat/templates/cambiar_contra.html
{% extends "inicio.html" %}

{% block titulo %}
<form action="" method="POST"> {% csrf_token %}

    {{form}}
    
    <button type="submit"> Cambiar Contraseña </button>
    
    </form>
    
{% endblock %}

AppCat/templates/editar_usuario.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="POST"> {% csrf_token %}

{{formu}}

<button type="submit"> Editar </button>

</form>

{% endblock %}

AppCat/templates/inicio.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />    
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="inicio.html">Inicio</a>
                <a class="navbar-brand" href="nuevo_cliente.html">Cliente</a>
                <a class="navbar-brand" href="crear_presupuesto.html">Presupuesto</a>
                <a class="navbar-brand" href="nueva_compra.html">Compra</a>
                <a class="navbar-brand" href="buscar_cliente.html">Buscar Cliente</a>
                {% if user.is_authenticated %}
                <a href="{% url 'Editar Usuario' %}">Hola {{user.first_name}} {{user.last_name}} - Editar  datos acá</a>
                {% if user.avatar_set.last %}
                <img src="{{user.avatar_set.last.imagen.url}}" width="70px" height="50px" alt="Foto del avatar del usuario activo.">
                {% else %}
                <img src="{% static 'AppCoder/assets/img/avatar-defecto.jpg' %}" width="70px" height="50px" alt="">
                
                {% endif %}
                <a href="{% url 'Agregar Avatar' %}">Cambiar Avatar Imagen</a>
                <a href="{% url 'Cambiar Contraseña' %}">Cambiar contra</a>
                <a class="btn btn-primary" href="{% url 'Cerrar Sesion' %}">Cerrar Sesion</a>
                {% else %}
                <a class="btn btn-primary" href="#signup">Registrarse</a>
                <a class="btn btn-primary" href="{% url 'Iniciar Sesion' %}">Iniciar Sesion</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block titulo %}
                                {% endblock %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block parrafo %}

        {% endblock %}         
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">Acerca de mi</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

AppCat/templates/inicio_sesion.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="POST"> {% csrf_token %}

{{formu}}

<button type="submit"> Inicia Sesión </button>

</form>

{% endblock %}

AppCat/templates/lista_de_compras.html
{{object_list}}

AppCat/templates/nueva_compra.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="post">{%csrf_token%}
    
    {{form}}

    <input type="submit" value="Guardar">

</form>
{% endblock %}

AppCat/templates/nuevo_avatar.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

{{formu}}

<button type="submit"> Crear Avatar </button>

</form>

{% endblock %}

AppCat/templates/nuevo_cliente.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="post">{%csrf_token%}
    
    {{form}}

    <input type="submit" value="Guardar">

</form>
{% endblock %}

AppCat/templates/registro.html
{% extends "inicio.html" %}

{% block parrafo %}

<form action="" method="POST"> {% csrf_token %}

{{formu}}

<button type="submit"> Registrarse </button>

</form>

{% endblock %}

AppCat/templates/resultadoBusqueda.html
{% extends "inicio.html" %}

{% block parrafo %}
<ol>
{% for cliente in nombre%}

    <li>{{Cliente.nombre%}}</li>

{%end for %}
</ol>
{% endblock %}

AppCat/templates/ver_compra.html
{% extends "inicio.html" %}

{% block titulo %}
Acá están las compras
{% endblock %}

AppCat/templates/ver_presupuesto.html
{% extends "inicio.html" %}

{% block titulo %}
Acá están los presupuesto
{% endblock %}